version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 158224
      POSTGRES_DB: chatapp
    volumes:
      - my_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: my_redis_container
    ports:
      - '6379:6379'

volumes:
  my_postgres_data:
